name: Test, Build and Release apk
env:
  JAVA_VERSION: '21'
  APP_VERSION: '0.0.3'
  APPCENTER_APP: 'patrick_jcq-29rr/FluApp'
  APK_PATH: 'build/app/outputs/apk/release/app-release.apk'

on:
    push:
      branches: [ "main" ]
jobs:
  build_deploy:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: "${{ env.JAVA_VERSION }}"
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        #flutter-version-file: pubspec.yaml
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build apk --build-name="${{ env.APP_VERSION }}"
    #--debug --split-per-abi
    - name: Install appcenter cli
      run: npm install -g appcenter-cli
    - name: Deploy App Center
      run: appcenter distribute release -f "${{ env.APK_PATH }}" -g probadores02 -a "${{ env.APPCENTER_APP }}" --token "${{ secrets.APPCENTER_TOKEN }}"